// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Models;

public partial class Student
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string RollNumber { get; set; }

    public string AadhaarNumber { get; set; }

    public string MobileNumber { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsActive { get; set; }
}