// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Models;

public partial class StudentFile
{
    public int Id { get; set; }
    public int? StudentId { get; set; }
    public string Shift { get; set; }
    public string? FileUploadName { get; set; }
    public DateTime? CreatedDate { get; set; }

}