// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LearningManagementSystem.Models;

public partial class UserDetail
{
    [Key]
    public int UserId { get; set; }

    public string Name { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Role { get; set; }

    public DateTime? CreatedDate { get; set; }

    public bool? IsActive { get; set; }
}